'use strict';
const { Relay } = require('./relay/server.js');
const { makeSession, generateKeyPair, exportPub, toAesKey, aeadEncr, aeadDecr, pad, unpad, TE, TD } = require('./cm-protocol.js');
(async () => {
  const relay = new Relay({ logging: false });
  const base = `http://127.0.0.1:${await relay.listen(0, '127.0.0.1')}`;
  const R=[]; const ok=(n,c,x='')=>{R.push(!!c);console.log(`${c?'PASS':'FAIL'}  ${n}${x?'  — '+x:''}`);};
  const api=async(p,o)=>(await (await fetch(base+p,o)).json());
  const mkQ=()=>api('/v1/queue',{method:'POST'});
  const push=(id,t,b)=>api(`/v1/queue/${id}/msg?t=${encodeURIComponent(t)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({blob:b})});
  const pull=(id,t,e,s=0)=>api(`/v1/queue/${id}/msg?token=${encodeURIComponent(t)}&epoch=${e}&since=${s}`);
  const rot=(id,t,e)=>api(`/v1/queue/${id}/rotate?token=${encodeURIComponent(t)}&epoch=${e}`,{method:'POST'});
  const enc=async(ch,m,burn)=>{const{mk,ephPub,seq}=await ch.send();const{iv,ct}=await aeadEncr(await toAesKey(mk),pad(TE.encode(m)));
    return JSON.stringify({v:1,seq,eph:ephPub,burn,body:{iv:Buffer.from(iv).toString('base64'),ct:Buffer.from(ct).toString('base64')}});};
  const dec=async(ch,blob)=>{const h=JSON.parse(blob);const mk=await ch.recv(h.eph);
    return TD.decode(unpad(await aeadDecr(await toAesKey(mk),new Uint8Array(Buffer.from(h.body.iv,'base64')),new Uint8Array(Buffer.from(h.body.ct,'base64')))));};
  const aKP=await generateKeyPair(),bKP=await generateKeyPair();
  const aPub=await exportPub(aKP),bPub=await exportPub(bKP);
  const qSend=await mkQ(),qRecv=await mkQ();
  const code=JSON.stringify({n:'VOID-A',k:aPub,recv:{id:qRecv.queueId,tok:qRecv.pushToken},send:{id:qSend.queueId,tok:qSend.pullToken,ep:qSend.pullEpoch}});
  ok('[1] A: 2 radhë + kod ftese',qSend.ok!==false&&qRecv.ok!==false&&code.length>40);
  const o=JSON.parse(code);
  const bSess=await makeSession(bKP,o.k);
  const bPull={queueId:o.send.id,tok:o.send.tok,epoch:o.send.ep,since:0};
  ok('[2] B: session + pull=qSend',!!bSess);
  await push(o.recv.id,o.recv.tok,JSON.stringify({type:'connect',pub:bPub,ghost:'RAVEN-B'}));
  ok('[2] B: connect te qRecv(A)',true);
  const pA=pull(qRecv.queueId,qRecv.pullToken,qRecv.pullEpoch,0);
  const conn=(await pA).msgs.map(m=>JSON.parse(m.blob)).find(x=>x.type==='connect');
  ok('[3] A: connect i kapur',!!conn&&conn.ghost==='RAVEN-B');
  await push(o.recv.id,o.recv.tok,await enc(bSess.out,'përshëndetje nga B',10));
  const pA2=pull(qRecv.queueId,qRecv.pullToken,qRecv.pullEpoch,(await pA).msgs.length?1:0);
  let allA=(await pA2).msgs.map(m=>JSON.parse(m.blob));const mB=allA.find(x=>x.v===1);
  const aSess=await makeSession(aKP,bPub);
  ok('[4] Chat B->A + BURN=10',mB&&mB.burn===10&&(await dec(aSess.inr,JSON.stringify(mB)))==='përshëndetje nga B');
  await push(qSend.queueId,qSend.pushToken,await enc(aSess.out,'përgjigje nga A',0));
  const pB=pull(bPull.queueId,bPull.tok,bPull.epoch,0);
  const mA=(await pB).msgs.map(m=>JSON.parse(m.blob)).find(x=>x.v===1);
  ok('[5] Chat A->B + READ-ONCE(0)',mA&&mA.burn===0&&(await dec(bSess.inr,JSON.stringify(mA)))==='përgjigje nga A');
  for(let i=0;i<5;i++)push(o.recv.id,o.recv.tok,await enc(bSess.out,'b'+i,-1));
  const rb=await rot(bPull.queueId,bPull.tok,bPull.epoch);
  const st=pull(bPull.queueId,o.send.tok,o.send.ep,0);
  ok('[6] RBQR + token vjetër refuzohet',rb.ok&&rb.pullEpoch===1&&!(await st).ok);
  ok('[7] TLP+Backup params',code.includes('recv')&&code.includes('send'));
  relay.stop();
  console.log(`\n====== MORS: ${R.filter(Boolean).length}/${R.length} PASS ======`);
  process.exitCode=R.every(Boolean)?0:1;
})().catch(e=>{console.error('ERR',e);process.exit(2);});